#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S2,     IRc,            sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     RightMotor,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     LeftMotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//This code finds the IR beacon and moves directly to it. as a result, it runs into the goals. :P
	task main()
	{
	while(true)
		{
			int IR = SensorValue[IRc]; //IF the IR Seeker is 5...
			if(IR == 5)
									{
							    motor[RightMotor] = 45;
									motor[LeftMotor] = 45;//Move it FORWARD.
									}


				else if(IR == 6) //OR if the IR is 6...
						    {
								motor[RightMotor] = 10;
								motor[LeftMotor] = 20;//Move it LEFT!
								}


					else if(IR == 7) //OR if the the IR is 7..
									{
									motor[RightMotor] = 10;//Move it LEFT!
								  motor[LeftMotor] = 20;
								  }


				  else if(IR == 8) //OR if the the IR is 8..
									{
									motor[RightMotor] = 10;//Move it LEFT!
								  motor[LeftMotor] = 20;
								  }


					else if(IR == 9) //OR if the the IR is 9..
									{
									motor[RightMotor] = 10;//Move it LEFT!
								  motor[LeftMotor] = 20;
								  }

					else if(IR == 4) //OR if the IR is 4..
						      {
						      motor[RightMotor] = 20; //Move it RIGHT!
						      motor[LeftMotor] = 10;
						      }


				  else if(IR == 3) //OR if the IR is 3..
						      {
						      motor[RightMotor] = 20; //Move it RIGHT!
						      motor[LeftMotor] = 10;
						      }


				  else if(IR == 2) //OR if the IR is 2..
						      {
						      motor[RightMotor] = 20; //Move it RIGHT!
						      motor[LeftMotor] = 10;
						      }


					else if(IR == 1) //OR if the IR is 1..
						      {
						      motor[RightMotor] = 20; //Move it RIGHT!
						      motor[LeftMotor] = 10;
						      }


		}
	}
