#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     IRc,            sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorB,          LeftGripper,   tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          RightGripper,  tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     LeftMotor,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     RightMotor,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int IR = SensorValue[IRc];

task main()
{
while(0==0)
{
		while(IR < 1)
		{
		motor[RightMotor] = 25;
		motor[LeftMotor] = 5;
		}

		if(IR < 5)
		{
		motor[RightMotor] = 25;
		motor[LeftMotor] = 5;
		}

    else if(IR > 5)
    {
    motor[RightMotor] = 5;
    motor[LeftMotor] = 25;
    }

    else if(IR == 5)
    {
    motor[RightMotor] = 0;
    motor[LeftMotor] = 0;
    wait1Msec(200);
    break;
    }



}


}
