#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     rightMotor,    tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     leftMotor,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     armMotor,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     inputMotor,    tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//





//This file is hereby declared the awesome work of Cruxien Farmer.
//Long live the king.





void movingforward(int drivespeed1, int encount1) //moves forward. duh.
{
		nMotorEncoder[leftMotor]=0; //Reset the encoders FIRST.
		nMotorEncoder[rightMotor]=0;
while(nMotorEncoder[rightMotor] <encount1)//while RIGHT motor's encoder is LESS THAN the encounts set in task main...
{
		motor[leftMotor]=	drivespeed1;//DRIVE the distance set in task main.
		motor[rightMotor]= drivespeed1;

}
		motor[leftMotor]= 0; //STOP
		motor[rightMotor]= 0;
}


void turningrightslight()//Turning right ever so Sliiiightly
{
		motor[leftMotor]= 100;
		motor[rightMotor]= 5;
		wait1Msec(485);
		motor[leftMotor]=0;
		motor[rightMotor]=0;
}


void movearm(int armspeed, int armencount)//moving the treads-arm up.
{
nMotorEncoder[armMotor]=0; //RESET tread's encoder
while(nMotorEncoder[armMotor] <armencount)//MOVE the arm up (set in task main)
{
		motor[armMotor]=	armspeed;//MOVE the arm at THIS SPEED (TASKMAIN)

}
		motor[armMotor]= 0;//STOP the arm.
}

void movetreads()//Moving the treads INSIDE the arm.
{
motor[inputMotor]= 50;//Treadmotor, blah, blah, blah.
wait1Msec(200);
motor[inputMotor]=0;
}

void turningleft() //TURN LEFT
{
		motor[leftMotor]= 5;
		motor[rightMotor]= 100;
		wait1Msec(1000);
		motor[leftMotor]=0;
		motor[rightMotor]=0;
}


void backup() //Back it up! back up that robot!
{
		motor[rightMotor]= -50;
		motor[leftMotor]= -50;
		wait1Msec(1000);
		motor[rightMotor]= 0;
		motor[leftMotor]= 0;
}


void turningright() //TURN RIGHT
{
		motor[leftMotor]= 100;
		motor[rightMotor]= 5;
		wait1Msec(1000);
		motor[leftMotor]=0;
		motor[rightMotor]=0;
}
task main()//MAIN TASK
{
movingforward(50, 350);//CALLING ALL FUNCTIONS! CALLING ALL FUNCTIONS! REPORT TO YOUR STATIONS! WE GOT A ROBOT TO RUN HERE!
turningrightslight();
movearm(50, 380);
movingforward(50, 2000);
movetreads();
backup();
turningleft();
movingforward(50, 1500);
turningright();
movingforward(50, 2000);
}
