#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorB,          LeftGripper,   tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          RightGripper,  tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     LeftMotor,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     RightMotor,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
 int threshold = 10;
task main
{
  while (true)
  {

		if(abs(joystick.joy1_y1) > threshold)
		{
			motor[LeftMotor] = -joystick.joy1_y1;
		}
		else
		{
			motor[LeftMotor] = 0;
		}


		if(abs(joystick.joy1_y2) > threshold)
		{
			motor[RightMotor] = joystick.joy1_y2;
		}
		else
		{
			motor[RightMotor] = 0;
    }


    if(joy1Btn(8))
	  {
	  motor[LeftGripper] = 50;
	  motor[RightGripper] = 50;
	  }
	  else if(joy1Btn(7))
	  {
	  motor[LeftGripper] = -50;
	  motor[RightGripper] = -50;
	  }
	  else
	  {
	  motor[LeftGripper] = 0;
	  motor[RightGripper] = 0;
	  }



  }
}
